2017-07-11 15:25:55,678 [Thread-2:6552] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop/index/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python3\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\new project\eshop\eshop\eshop\urls.py", line 22, in <module>
    url(r'^shop/', include('shop.urls', namespace='shop')),
  File "D:\virtualenv_python\eshop\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Python3\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\new project\eshop\eshop\shop\urls.py", line 9, in <module>
    from shop import views
  File "D:\new project\eshop\eshop\shop\views.py", line 8, in <module>
    from utils.my_logger import logger
ImportError: cannot import name 'logger'
2017-07-11 15:30:49,502 [Thread-2:9480] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop/detail/29/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 564, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'eshop.shop_cart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 501, in render
    current_app=current_app)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 574, in reverse
    key)
django.core.urlresolvers.NoReverseMatch: 'eshop.shop_cart' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop\views.py", line 54, in get
    return render(request, 'shop/detail.html', content)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\utils\six.py", line 686, in reraise
    raise value
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'add_cart' with arguments '(29,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['shop_cart/add_cart/$']
2017-07-11 15:34:31,748 [Thread-11:8936] [django.request:170] [base:get_response] [WARNING]- Not Found: /user/user_center_Info/
2017-07-11 15:39:20,327 [Thread-8:5568] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-11 16:34:40,557 [Thread-21:9396] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 24, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:35:29,395 [Thread-4:10408] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 25, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:36:27,423 [Thread-4:1384] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 25, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:36:32,378 [Thread-5:11172] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 25, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:37:19,893 [Thread-4:8160] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 24, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:37:58,555 [Thread-4:5852] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 25, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:38:06,788 [Thread-5:5348] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 25, in get
    ShopCart.objects.create(user=user_id, goods_info=nid, count=count)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\query.py", line 346, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\db\models\fields\related.py", line 642, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "10": "ShopCart.user" must be a "UserProfile" instance.
2017-07-11 16:40:50,125 [Thread-9:7200] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/shop_cart/shopcart/1/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 675, in resolve
    new_obj = func(obj, *arg_vals)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaultfilters.py", line 45, in _dec
    args[0] = force_text(args[0])
  File "D:\virtualenv_python\eshop\lib\site-packages\django\utils\encoding.py", line 90, in force_text
    s = six.text_type(s)
TypeError: __str__ returned non-string (type GoodsInfo)
2017-07-11 16:41:47,505 [Thread-2:9668] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/shop_cart/shopcart/1/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\base.py", line 675, in resolve
    new_obj = func(obj, *arg_vals)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\template\defaultfilters.py", line 45, in _dec
    args[0] = force_text(args[0])
  File "D:\virtualenv_python\eshop\lib\site-packages\django\utils\encoding.py", line 90, in force_text
    s = six.text_type(s)
TypeError: __str__ returned non-string (type GoodsInfo)
2017-07-11 16:45:58,729 [Thread-6:8100] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 20, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:46:47,058 [Thread-5:10176] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:47:04,097 [Thread-6:8628] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:47:39,578 [Thread-4:10176] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:48:11,284 [Thread-4:8576] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:48:53,069 [Thread-4:9936] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:49:28,879 [Thread-7:7640] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    if len(cart) != 0:
TypeError: object of type 'int' has no len()
2017-07-11 16:53:11,100 [Thread-17:11128] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/new project/eshop/eshop\shop_cart\views.py", line 22, in get
    cart.count += goods_num
TypeError: unsupported operand type(s) for +=: 'method' and 'str'
2017-07-11 16:54:30,619 [Thread-9:3344] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/new project/eshop/eshop\shop_cart\views.py", line 22, in get
    cart.count += goods_num
TypeError: unsupported operand type(s) for +=: 'method' and 'str'
2017-07-11 17:08:20,987 [Thread-5:8772] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\new project\eshop\eshop\shop_cart\views.py", line 21, in get
    cart[0].count += goods_num
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2017-07-11 17:10:33,344 [Thread-9:9544] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/new project/eshop/eshop\shop_cart\views.py", line 21, in get
    cart.first().count += goods_num
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2017-07-11 17:10:46,959 [Thread-10:9316] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/new project/eshop/eshop\shop_cart\views.py", line 21, in get
    cart.first().count += goods_num
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2017-07-11 17:14:44,292 [Thread-9:4284] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/28/
Traceback (most recent call last):
  File "D:\virtualenv_python\eshop\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv_python\eshop\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/new project/eshop/eshop\shop_cart\views.py", line 22, in get
    cart.count =cart.count + goods_num
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2017-07-12 02:24:11,000 [Thread-11:139992281954048] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 02:44:16,179 [Thread-107:139991908873984] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 02:46:41,125 [Thread-128:139991866910464] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop/detail/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop/views.py", line 41, in get
    goods_info.save()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/haystack/signals.py", line 52, in handle_save
    index.update_object(instance, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/haystack/indexes.py", line 284, in update_object
    backend.update(self, [instance])
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/haystack/backends/whoosh_cn_backend.py", line 178, in update
    self.setup()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/haystack/backends/whoosh_cn_backend.py", line 119, in setup
    self.content_field_name, self.schema = self.build_schema(connections[self.connection_alias].get_unified_index().all_searchfields())
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/haystack/backends/whoosh_cn_backend.py", line 163, in build_schema
    schema_fields[field_class.index_fieldname] = TEXT(stored=True, analyzer=ChineseAnalyzer(), field_boost=field_class.boost, sortable=True)
NameError: name 'ChineseAnalyzer' is not defined
2017-07-12 02:47:51,478 [Thread-129:139991866910464] [django.request:170] [base:get_response] [WARNING]- Not Found: /home/index
2017-07-12 02:54:29,196 [Thread-43:140414728263424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/58/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 25, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=goods_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-12 02:54:32,491 [Thread-44:140414728263424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/58/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 25, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=goods_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-12 02:54:34,168 [Thread-45:140414728263424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/58/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 25, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=goods_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-12 02:54:35,082 [Thread-46:140414728263424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/58/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 25, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=goods_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-12 02:55:27,712 [Thread-50:140414736656128] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/58/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 25, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=goods_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-12 02:57:02,805 [Thread-4:139689157523200] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/58/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 26, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=goods_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-12 03:51:13,547 [Thread-6:140523162457856] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop/list/4/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/smartif.py", line 177, in translate_token
    op = OPERATORS[token]
KeyError: 'ordering=="0"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop/views.py", line 118, in get
    return render(request, 'shop/list.html', content)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/defaulttags.py", line 1013, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/defaulttags.py", line 945, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/defaulttags.py", line 948, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/base.py", line 424, in compile_filter
    return FilterExpression(token, self)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/base.py", line 640, in __init__
    "from '%s'" % (token[upto:], token))
django.template.base.TemplateSyntaxError: Could not parse the remainder: '=="0"' from 'ordering=="0"'
2017-07-12 04:06:29,463 [Thread-6:140596050679552] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop/detail/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop/views.py", line 56, in get
    UseRedis.write_to_cache(user_id, recently_browsed)
TypeError: write_to_cache() missing 1 required positional argument: 'content'
2017-07-12 04:06:31,220 [Thread-7:140596033283840] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop/detail/29/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop/views.py", line 56, in get
    UseRedis.write_to_cache(user_id, recently_browsed)
TypeError: write_to_cache() missing 1 required positional argument: 'content'
2017-07-11 20:37:58,365 [Thread-68:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:37:59,808 [Thread-69:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:00,633 [Thread-70:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:01,220 [Thread-71:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:01,575 [Thread-72:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:01,840 [Thread-73:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:02,089 [Thread-74:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:02,337 [Thread-75:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:02,560 [Thread-76:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:03,643 [Thread-77:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:03,864 [Thread-78:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:38:04,050 [Thread-79:139837122262784] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:53:40,445 [Thread-17:140376964589312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:53:41,555 [Thread-18:140376964589312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:53:42,947 [Thread-19:140376964589312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:54:24,387 [Thread-24:140376964589312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:54:24,871 [Thread-25:140376964589312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:54:25,360 [Thread-26:140376964589312] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:55:04,447 [Thread-33:140376947803904] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view shop_cart.views.AddCartView didn't return an HttpResponse object. It returned None instead.
2017-07-11 20:57:07,238 [Thread-39:140376972982016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:57:44,840 [Thread-42:140376972982016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:57:56,201 [Thread-45:140376972982016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:58:08,269 [Thread-46:140376972982016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 23, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 20:58:49,743 [Thread-4:140477056366336] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 24, in get
    cart.count = int(goods_num)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2017-07-11 21:20:44,696 [Thread-4:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:21:45,750 [Thread-7:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:21:51,306 [Thread-8:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:21:53,927 [Thread-9:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:21:54,675 [Thread-10:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:21:55,282 [Thread-11:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:22:01,875 [Thread-12:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 32, in get
    logger.info()
TypeError: info() missing 1 required positional argument: 'msg'
2017-07-11 21:22:22,474 [Thread-13:140313561659136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view shop_cart.views.AddCartView didn't return an HttpResponse object. It returned None instead.
2017-07-11 21:25:12,323 [Thread-10:140116717610752] [django.request:170] [base:get_response] [WARNING]- Not Found: /home/index/
2017-07-11 21:25:12,458 [Thread-11:140116717610752] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-11 21:25:12,575 [Thread-12:140116717610752] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-11 21:55:38,375 [Thread-8:139812711421696] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/my_cart/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 41, in get
    return render(request,'shop_cart/cart.html', content)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/backends/django.py", line 72, in render
    context = make_context(context, request)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 272, in make_context
    context.push(original_context)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 55, in push
    return ContextDict(self, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 20, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
2017-07-11 21:57:15,213 [Thread-17:139812703028992] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/my_cart/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 41, in get
    return render(request,'shop_cart/cart.html', content)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/backends/django.py", line 72, in render
    context = make_context(context, request)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 272, in make_context
    context.push(original_context)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 55, in push
    return ContextDict(self, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 20, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 9; 2 is required
2017-07-11 21:57:43,240 [Thread-3:140165698070272] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/my_cart/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 41, in get
    return render(request,'shop_cart/cart.html', content)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/backends/django.py", line 72, in render
    context = make_context(context, request)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 272, in make_context
    context.push(original_context)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 55, in push
    return ContextDict(self, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/template/context.py", line 20, in __init__
    super(ContextDict, self).__init__(*args, **kwargs)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
2017-07-11 21:58:56,709 [Thread-4:140444278380288] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/images/goods/goods012.jpg
2017-07-11 22:06:22,324 [Thread-7:140444262295296] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:06:22,342 [Thread-8:140444253902592] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:06:22,351 [Thread-6:140444278380288] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:07:35,718 [Thread-3:139695844837120] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:07:35,731 [Thread-5:139695623239424] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:07:35,745 [Thread-4:139695836444416] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:11:12,691 [Thread-4:140589676070656] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:11:12,702 [Thread-5:140589667677952] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:11:12,703 [Thread-3:140589684463360] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:11:45,644 [Thread-3:139817745946368] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:11:45,658 [Thread-5:139817729160960] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:11:45,680 [Thread-4:139817737553664] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:15:31,541 [Thread-4:140556495746816] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:15:31,558 [Thread-3:140556711737088] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:15:31,582 [Thread-5:140556487354112] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:20:59,776 [Thread-3:139806704191232] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:20:59,787 [Thread-4:139806487082752] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:20:59,789 [Thread-5:139806712583936] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:21:01,596 [Thread-8:139806704191232] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:21:01,612 [Thread-7:139806487082752] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:21:01,624 [Thread-9:139806712583936] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:21:02,404 [Thread-12:139806712583936] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:21:02,410 [Thread-11:139806487082752] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:21:02,424 [Thread-13:139806704191232] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:21:03,048 [Thread-15:139806487082752] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:21:03,054 [Thread-16:139806704191232] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 22:21:03,072 [Thread-17:139806712583936] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:21:03,580 [Thread-19:139806487082752] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/59251bebNea0fc46f.jpg
2017-07-11 22:21:03,582 [Thread-21:139806704191232] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58e62d46Ndcc0a865.jpg
2017-07-11 22:21:03,601 [Thread-20:139806712583936] [django.request:170] [base:get_response] [WARNING]- Not Found: /shop_cart/my_cart/goods/58ec98efN3db99134.jpg
2017-07-11 23:18:16,132 [Thread-48:140584978573056] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 29, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=buy_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-11 23:18:26,808 [Thread-49:140584978573056] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /shop_cart/add_cart/30/
Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gogo/django/eshop/eshop/shop_cart/views.py", line 29, in get
    ShopCart.objects.create(user_id=user_id, goods_info_id=nid, count=buy_num)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gogo/.virtualenvs/eshop/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-07-11 23:45:43,647 [Thread-180:140584978573056] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-11 23:45:43,659 [Thread-181:140584715007744] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 00:23:49,807 [Thread-3:139693869246208] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 01:19:59,333 [Thread-3:140042496263936] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 13:13:54,789 [Thread-10:139971484440320] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 13:13:55,957 [Thread-14:139971501225728] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-12 16:15:54,642 [Thread-10:139999848302336] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
